### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by trhodeos** [n64dev/cen64#87]
I'm interested in implementing a debugger, although I'm not 100% sure what that'd entail. I see the QT skeleton for a debugger UI. I don't really care what the UI (or cli) is. The first thing I'd like to be able to do is to set breakpoints and inspect registers/variables/etc.

I'm going to start looking into this, but any pointers are very much appreciated :)

**Comment by fraser125** [comment]
It can get a bit technical, I've started looking myself but haven't gotten past the research stage yet.

The first step is understanding Interrupt and Exception handling in the MIPS processor. ("See MIPS Run", book/pdf is a great start). Generally (but not always) this will require MIPS assembly language. 

I've written some of my research/plans about [Exceptions/Interrupts](https://sites.google.com/site/consoleprotocols/home/n64-assembly-home/Ref-Exceptions-and-Interrupts), my concept is stand-alone (written before I knew about libn64) but may provide a different perspective to understand it better. 

The exception handler to integrate with would be the one in [libn64](https://github.com/tj90241/n64chain/blob/master/libn64/os/asm/exception.s) 

Then you have to choose to support remote and/or local debugging. Local debugging would require all of the GUI code to be created as well as the above mentioned hook. I would suggest remote debugging you only have to create a hook and a stub (details below). The downside to remote debugging is you need a way to communicate with the console. The recommended way would be with a FLASH cartridge that has USB communication (i.e. 64Drive, Everdrive v3). 

Once you have a hook in place you need to write what's called a gdb stub. There is an old one [(Linux 2.6)](https://elixir.bootlin.com/linux/v2.6.26.8/source/arch/mips/kernel/gdb-stub.c) written in C, combined with the [latest gdb protocol specification](https://sourceware.org/gdb/current/onlinedocs/gdb/Remote-Protocol.html) that would be the way to go. 

The Exception/Interrupt handler is a little involved because of the use of assembly language. The other "hard" part is debugging a debugger before you have a debugger. Maybe if @tj90241 or someone else can implement the hooks in the Interrupt exception handler the other pieces can be divided up for the community to develop.

There are many other more knowledgable people that may also respond, if they post corrections trust them.

**Comment by tj90241** [comment]
The QI GUI was really my foray into UI design.

The actual debug "protocol" (if you can even call it that at this point) is all in `device/netapi.{c,h}`. My initial idea was to have the debugger communicate with the emulator over TCP/IP. There was a `-debug` option that at one point worked in conjunction with the UI, but has not been tested in ages. The `-debug` option would hang the emulator until the UI connected to it.

The actual development of the debugger will be pretty challenging, since all the pipelines closely model what the hardware is doing. So, for instance, to get the committed register view (the view of the "architectural" registers), you need to access the RF and apply the write sitting in the WB stage, if the latch in the WB stage indicates that the instruction is not cancelled. Also true for the program counter.

If you wanted a processor's view of the memory, keep in mind that some of it would be cached, so you would need to overlay the view of the cache on top of what it's in the RDRAM structure to ultimately produce a view of cached memory. I'm not sure how you would go about exposing virtual addresses outside of the TLB, given that the MIPS TLB is not hardware-architectured like x86's is.

**Comment by sp1187** [comment]
Closed as GDB debugger support was added by PR #187.
